Task : SelectionModel
Experiment : SelectionModel
seed : 42
data: 
    train : /home/jisukim/playground-NLP/DPR/selected_model/datasets/train_top10_dataset.parquet
    valid: /home/jisukim/playground-NLP/DPR/selected_model/datasets/valid_top10_dataset.parquet
    batch_size: 128
    max_length: 512
    output_dir: output_top1
model:
    model_name: klue/roberta-base
    epoch: 5